upstream api_pool {
    server api_1:3000;
    server api_2:3000;
    server api_3:3000;
}

server {
    listen 80;

    location / {
        proxy_pass http://api_pool;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
